import type { CaptionTrack } from "./types";

export interface TrackSelectionHints {
  /** vssId of the track currently shown in the player, if detectable (best-effort). */
  activeVssId?: string | undefined;
  /** Preferred caption language code to fall back to when no track is active. */
  defaultLanguageCode?: string | undefined;
}

/**
 * Pick which caption track to copy (SPEC §2).
 * 1. Follow the currently-active track when known.
 * 2. Otherwise prefer the default language, choosing manual over auto-generated.
 * 3. Otherwise the first available track.
 */
export function selectCaptionTrack(
  tracks: CaptionTrack[],
  hints: TrackSelectionHints,
): CaptionTrack | undefined {
  if (tracks.length === 0) return undefined;

  if (hints.activeVssId !== undefined) {
    const active = tracks.find((t) => t.vssId === hints.activeVssId);
    if (active !== undefined) return active;
  }

  const inLanguage =
    hints.defaultLanguageCode === undefined
      ? []
      : findTracksInLanguage(tracks, hints.defaultLanguageCode);
  const pool = inLanguage.length > 0 ? inLanguage : tracks;

  const manual = pool.find((t) => !isAutoGenerated(t));
  return manual ?? pool[0];
}

function findTracksInLanguage(tracks: CaptionTrack[], languageCode: string): CaptionTrack[] {
  const preferred = languageCode.toLowerCase();
  const exact = tracks.filter((track) => track.languageCode.toLowerCase() === preferred);
  if (exact.length > 0) return exact;

  const primary = preferred.split("-")[0];
  if (primary === undefined) return [];
  return tracks.filter((track) => track.languageCode.toLowerCase().split("-")[0] === primary);
}

function isAutoGenerated(track: CaptionTrack): boolean {
  return track.kind === "asr" || track.vssId?.startsWith("a.") === true;
}
